version: '3.3'
services:

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - ./config/mongo:/data/db
      - ./config/mongo/zzzmongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./config/mongo/zzzmongo.conf:/etc/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
             
#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    ports:
#      - "443:443"
#    networks:
#      - backend
#    depends_on:
#      - mernapp
#    volumes:
#      - ./mernapp/dist:/srv/www/static
#      - ./config/nginx/nginx/:/etc/nginx/
#      - ./config/nginx/certs/:/etc/nginx/certs/
#
#  mernapp:
#    container_name: mernapp
#    build:
#      context: './mernapp'
#      dockerfile: 'Dockerfile'
#    env_file:
#      - ./.env
#    ports:
#      - "3000:3000"
#      - "9229:9229"
#    networks:
#      - backend
#    depends_on:
#      - mongodb
#    environment:
#      - NODE_ENV=production
#      - DATABASE_HOST=${DATABASE_HOST}
#      - DATABASE_PORT=${DATABASE_PORT}
#      - DATABASE_USER=${DATABASE_USER}
#      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
#      - DATABASE_NAME=${DATABASE_NAME}
#      - DATABASE_CONNECTION_OPTIONS=${DATABASE_CONNECTION_OPTIONS}
#      - DOCKER_COMPOSE=true

      
networks:
  backend:
    name: mongodbnet
    driver: bridge
