version: '3'
services:
  mern:
    build: 
      context: './mernapp'
      dockerfile: 'Dockerfile.dev'
    ports:
      - "3000:3000"
    depends_on: 
      - mongodb
    volumes:
      - "./mernapp:/app"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
      - DATABASE_USER=user
      - DATABASE_PASSWORD=secret_password
      - DATABASE_NAME=mernproject
      - DATABASE_CONNECTION_OPTIONS=none
      - DOCKER_COMPOSE=true
  gamestats:
    build: 
      context: './gamestats'
      dockerfile: 'Dockerfile'
    depends_on: 
      - mongodb
    environment:
      - NODE_ENV=development

  mongodb:
    image: mongo:latest
    volumes:
      - ./config/amongo:/data/db
      - ./config/amongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpword
      - MONGO_INITDB_DATABASE=admin
      
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./mernapp/dist:/srv/www/static
      - ./config/anginx/nginxConfig.conf:/etc/nginx/conf.d/default.conf
      - ./config/anginx:/etc/nginx/ssl
    depends_on:
      - mern
      - gamestats
    