FROM bitnami/node:latest

COPY . /app
WORKDIR /app

EXPOSE 3000

CMD bash -c "NODE_ENV=development; npm install; npm run build; echo ===; echo ===; echo ===; echo === App built and launching ===; npm run development;"